- name: Install Elastic Search 
  package:
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{VERSION}}-x86_64.rpm
    state: installed 

- name: Change the network host IP 
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml 
    regex: "network.host"
    line: "network.host: 0.0.0.0"
  
