- name: Install Kibana 
  package:
    name: https://artifacts.elastic.co/downloads/kibana/kibana-{{VERSION}}-x86_64.rpm 
    state: installed 

- name: Update network info in Kibana 
  lineinfile:
    path: /etc/kibana/kibana.yml 
    regex: "server.host: \"localhost\""
    line: "server.host: \"0.0.0.0\""

- name: Start kibana service 
  service:
    name: 