- name: Install and configure Kuburnetes Master Node
  hosts: all
  become: yes
  vars:
    MASTER: kube-master
  tasks:
    - debug:
        msg: |
          Note: This automation works only if you set the hostname of the servers as kube-master for master node, Otherwise it is going to fail

    - wait_for: timeout=3

    - name: Create Kuburnetes Yum repo file
      blockinfile:
        path: /etc/yum.repos.d/kuburnetes.repo
        create: yes
        block: |
          [kuburnetes]
          name=virt7-docker-common-release
          baseurl=http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
          gpgcheck=0
          enabled=1

    - name: Install required packages
      yum:
        name: "{{item}}"
        state: latest
        update_cache: yes
        enablerepo: kuburnetes
      with_items:
        - etcd
        - flannel
        - kubernetes

    - name: Update Kuburnetes config 
      lineinfile:
        path: /etc/kubernetes/config
        regexp: '^KUBE_MASTER'
        line: KUBE_MASTER="--master=http://{{MASTER}}:8080"

    - name: Update etcd config
      replace:
        path: /etc/etcd/etcd.conf
        regexp: "localhost"
        replace: '0.0.0.0'

    - name: Update apiserver config 
      blockinfile:
        path: /etc/kubernetes/apiserver
        block: |
          KUBE_API_ADDRESS="--insecure-bind-address=0.0.0.0"
          KUBE_API_PORT="--port=8080"
          KUBELET_PORT="--kubelet-port=10250"
          KUBE_ETCD_SERVERS="--etcd-servers=http://{{MASTER}}:2379"
          KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range=10.254.0.0/16"
          KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"
          KUBE_API_ARGS=""











