- name: Install maven tool
  hosts: all
  become: yes
  tasks:
    - name: Get latest version of maven
      shell: curl http://maven.apache.org/download.cgi | grep http | grep bin.tar.gz | awk -F '[=",">]' '{print $4}' | grep ^http
      register: out

    - name: Download Maven3
      unarchive: 
        dest: /opt
        url: "{{out.stdout}}"
        remote_src: true

#- name: Unpack Maven3
#  action: command creates=/opt/maven chdir=/opt tar zxvf /opt/maven3.tar.gz
 
#- name: Create Maven3 directory link
#  file: path=/opt/maven src=/opt/apache-maven-3.0.4 state=link
  
#- name: Set mvn link
#  action: command update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 1
